version: '3.8'  # Docker Compose Version

services:
  movie-management:
    image: quarkus/movie-management-jvm  # Image name
    build:
      context: .  # The build directory
      dockerfile: src/main/docker/Dockerfile.jvm  # The path to Dockerfile
    ports:
      - "8080:8080"  # Port forwarding 8080
    environment:
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    restart: unless-stopped  # Reboot option
